main: testplugin.App
name: firstplugin
version: 0.1
author: Mystic
api-version: 1.21.5
commands:
  givecustomitem:
    description: Give Custom Chest
    permission: testplugin.use
    usage: /givecustomitem <player> <level> [count]